# App runs on this port
server.port=${PORT:8080}
#spring.data.mongodb.uri=mongodb://localhost:27017/inventory_management
spring.data.mongodb.auto-index-creation=true
app.jwt.expirationMinutes=${JWT_EXPIRATION_MINUTES:3600}
app.jwt.secret=${JWT_SECRET}

# MongoDB
spring.data.mongodb.uri=${MONGO_URI}