# App runs on this port
server.port=9000

# JWT Settings
app.jwt.expirationMinutes=3600
app.jwt.secret=i-am-a-super-secret-i-am-a-super-secret-i-am-a-super-secret

spring.data.mongodb.uri=mongodb://localhost:23547017/inventory_management
spring.data.mongodb.auto-index-creation=true