# App runs on this port
server.port=${PORT:8080}


# JWT Settings
app.jwt.expirationMinutes=3600
app.jwt.secret=i-am-a-super-secret-i-aam-a-super-secret-i-am-a-super-secret

spring.data.mongodb.uri=mongodb+srv://velshanth_db_user:velshanth_db_user@cluster0.wgtbufq.mongodb.net/inventory_management?retryWrites=true&w=majority
#spring.data.mongodb.uri=mongodb://localhost:27017/inventory_management
spring.data.mongodb.auto-index-creation=true